'use strict';

const { toKebabCase } = require('./entity-engine');

const OPENAPI_TYPE = {
  text: 'string', string: 'string', richText: 'string',
  integer: 'integer', int: 'integer',
  number: 'number', float: 'number', real: 'number', money: 'number',
  boolean: 'boolean', bool: 'boolean',
  date: 'string', timestamp: 'string', email: 'string', link: 'string',
  password: 'string', choice: 'string', location: 'string',
  file: 'string', image: 'string', group: 'string', json: 'string',
};

function generateOpenApiSpec(core) {
  const spec = {
    openapi: '3.0.0',
    info: { title: core.name, version: '1.0.0', description: `API generated by ChadStart for "${core.name}"` },
    paths: {},
    components: {
      schemas: {},
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    },
  };

  // Auth endpoints for authenticable entities
  for (const e of Object.values(core.authenticableEntities || {})) {
    const slug = e.slug;
    spec.components.schemas[e.name] = authSchema(e);
    spec.components.schemas[`${e.name}Input`] = authInputSchema(e);
    spec.components.schemas[`${e.name}LoginInput`] = loginSchema();
    spec.components.schemas[`${e.name}AuthResponse`] = { type: 'object', properties: { token: { type: 'string' }, user: { $ref: `#/components/schemas/${e.name}` } } };

    spec.paths[`/api/auth/${slug}/signup`] = { post: { tags: [`Auth – ${e.name}`], summary: `Sign up as ${e.name}`, requestBody: jsonBody(`${e.name}Input`), responses: { 201: jsonResp(e.name + 'AuthResponse'), 400: desc('Validation error'), 409: desc('Email already registered') } } };
    spec.paths[`/api/auth/${slug}/login`]  = { post: { tags: [`Auth – ${e.name}`], summary: `Login as ${e.name}`, requestBody: jsonBody(`${e.name}LoginInput`), responses: { 200: jsonResp(e.name + 'AuthResponse'), 401: desc('Invalid credentials') } } };
    spec.paths[`/api/auth/${slug}/me`]     = { get: { tags: [`Auth – ${e.name}`], summary: `Get current ${e.name}`, security: [{ bearerAuth: [] }], responses: { 200: jsonResp(e.name), 401: desc('Unauthorized') } } };
  }

  // Entity CRUD endpoints
  for (const e of Object.values(core.entities)) {
    const base = `/api/${e.slug}s`;
    const tag = e.name;
    const sec = (rule) => hasSecurity(e, rule) ? { security: [{ bearerAuth: [] }] } : {};

    if (!e.authenticable) {
      spec.components.schemas[e.name] = entitySchema(e, core.entities);
      spec.components.schemas[`${e.name}Input`] = entityInputSchema(e, core.entities);
    }

    if (e.single) {
      spec.paths[base] = {
        get:   { tags: [tag], summary: `Get ${e.name}`, ...sec('read'), responses: { 200: jsonResp(e.name), 404: desc('Not Found') } },
        patch: { tags: [tag], summary: `Update ${e.name}`, ...sec('update'), requestBody: jsonBody(`${e.name}Input`), responses: { 200: jsonResp(e.name), 404: desc('Not Found') } },
      };
    } else {
      spec.paths[base] = {
        get:  { tags: [tag], summary: `List all ${e.name}s`, ...sec('read'), parameters: e.properties.map((p) => ({ name: p.name, in: 'query', required: false, schema: { type: 'string' } })), responses: { 200: { description: 'OK', content: { 'application/json': { schema: { type: 'array', items: { $ref: `#/components/schemas/${e.name}` } } } } } } },
        post: { tags: [tag], summary: `Create a ${e.name}`, ...sec('create'), requestBody: jsonBody(`${e.name}Input`), responses: { 201: jsonResp(e.name), 400: desc('Bad Request') } },
      };
      spec.paths[`${base}/{id}`] = {
        get:    { tags: [tag], summary: `Get ${e.name} by id`, ...sec('read'), parameters: [idParam()], responses: { 200: jsonResp(e.name), 404: desc('Not Found') } },
        patch:  { tags: [tag], summary: `Update ${e.name}`, ...sec('update'), parameters: [idParam()], requestBody: jsonBody(`${e.name}Input`), responses: { 200: jsonResp(e.name), 404: desc('Not Found') } },
        delete: { tags: [tag], summary: `Delete ${e.name}`, ...sec('delete'), parameters: [idParam()], responses: { 200: desc('Deleted'), 404: desc('Not Found') } },
      };
    }
  }

  // Custom endpoints
  for (const [name, ep] of Object.entries(core.endpoints || {})) {
    const p = `/endpoints${ep.path}`;
    spec.paths[p] = spec.paths[p] || {};
    spec.paths[p][ep.method.toLowerCase()] = { tags: ['Endpoints'], summary: ep.description || name, responses: { 200: desc('OK') } };
  }

  // File storage
  for (const [bucket] of Object.entries(core.files || {})) {
    spec.paths[`/files/${bucket}`] = { post: { tags: ['Files'], summary: `Upload to ${bucket}`, requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' } } } } } }, responses: { 200: desc('Uploaded') } } };
    spec.paths[`/files/${bucket}/{file}`] = { get: { tags: ['Files'], summary: `Download from ${bucket}`, parameters: [{ name: 'file', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: desc('File content'), 404: desc('Not Found') } } };
  }

  return spec;
}

// ─── Schema helpers ─────────────────────────────────────────────────────────

function entitySchema(e, all) {
  const props = { id: { type: 'integer', readOnly: true } };
  for (const p of e.properties) props[p.name] = { type: OPENAPI_TYPE[p.type] || 'string' };
  for (const r of e.belongsTo || []) {
    const ref = all[typeof r === 'string' ? r : (r.entity || r.name)];
    if (ref) props[`${ref.tableName}_id`] = { type: 'integer' };
  }
  return { type: 'object', properties: props };
}

function entityInputSchema(e, all) {
  const s = entitySchema(e, all);
  const { id, ...rest } = s.properties;
  return { type: 'object', properties: rest };
}

function authSchema(e) {
  const props = { id: { type: 'integer', readOnly: true }, email: { type: 'string', format: 'email' } };
  for (const p of e.properties) props[p.name] = { type: OPENAPI_TYPE[p.type] || 'string' };
  return { type: 'object', properties: props };
}

function authInputSchema(e) {
  const props = { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } };
  for (const p of e.properties) props[p.name] = { type: OPENAPI_TYPE[p.type] || 'string' };
  return { type: 'object', required: ['email', 'password'], properties: props };
}

function loginSchema() {
  return { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } };
}

function hasSecurity(e, rule) {
  const list = (e.policies || {})[rule];
  if (list && list.length) return list[0].access !== 'public';
  return true; // default: requires auth
}

function jsonBody(schema) { return { required: true, content: { 'application/json': { schema: { $ref: `#/components/schemas/${schema}` } } } }; }
function jsonResp(schema) { return { description: 'OK', content: { 'application/json': { schema: { $ref: `#/components/schemas/${schema}` } } } }; }
function desc(d) { return { description: d }; }
function idParam() { return { name: 'id', in: 'path', required: true, schema: { type: 'integer' } }; }

module.exports = { generateOpenApiSpec };
