'use strict';

const { toKebabCase } = require('./entity-engine');

/**
 * Generate an OpenAPI 3.0 specification from the core model.
 */
function generateOpenApiSpec(core) {
  const spec = {
    openapi: '3.0.0',
    info: {
      title: core.name,
      version: '1.0.0',
      description: `API generated by ChadStart for "${core.name}"`,
    },
    paths: {},
    components: {
      schemas: {},
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
  };

  // ── Auth endpoints per user collection ──────────────────────────────────
  for (const uc of Object.values(core.userCollections || {})) {
    const slug = toSlug(uc.name);
    const ucSchema = buildUserCollectionSchema(uc);
    spec.components.schemas[uc.name] = ucSchema;
    spec.components.schemas[`${uc.name}Input`] = buildUserCollectionInputSchema(uc);
    spec.components.schemas[`${uc.name}LoginInput`] = {
      type: 'object',
      required: ['email', 'password'],
      properties: {
        email: { type: 'string', format: 'email' },
        password: { type: 'string', format: 'password' },
      },
    };
    spec.components.schemas[`${uc.name}AuthResponse`] = {
      type: 'object',
      properties: {
        token: { type: 'string' },
        user: { $ref: `#/components/schemas/${uc.name}` },
      },
    };

    spec.paths[`/auth/${slug}/signup`] = {
      post: {
        tags: [`Auth – ${uc.name}`],
        summary: `Sign up as ${uc.name}`,
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: `#/components/schemas/${uc.name}Input` } } },
        },
        responses: {
          201: { description: 'Created', content: { 'application/json': { schema: { $ref: `#/components/schemas/${uc.name}AuthResponse` } } } },
          400: { description: 'Validation error' },
          409: { description: 'Email already registered' },
        },
      },
    };

    spec.paths[`/auth/${slug}/login`] = {
      post: {
        tags: [`Auth – ${uc.name}`],
        summary: `Login as ${uc.name}`,
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: `#/components/schemas/${uc.name}LoginInput` } } },
        },
        responses: {
          200: { description: 'OK', content: { 'application/json': { schema: { $ref: `#/components/schemas/${uc.name}AuthResponse` } } } },
          401: { description: 'Invalid credentials' },
        },
      },
    };

    spec.paths[`/auth/${slug}/me`] = {
      get: {
        tags: [`Auth – ${uc.name}`],
        summary: `Get current ${uc.name}`,
        security: [{ bearerAuth: [] }],
        responses: {
          200: { description: 'OK', content: { 'application/json': { schema: { $ref: `#/components/schemas/${uc.name}` } } } },
          401: { description: 'Unauthorized' },
        },
      },
    };
  }

  // ── Entity CRUD endpoints ────────────────────────────────────────────────
  for (const entity of Object.values(core.entities)) {
    const tag = entity.name;
    const basePath = `/api/${toKebabCase(entity.name)}s`;
    const schema = buildEntitySchema(entity, core.entities);

    spec.components.schemas[entity.name] = schema;
    spec.components.schemas[`${entity.name}Input`] = {
      ...schema,
      properties: Object.fromEntries(
        Object.entries(schema.properties).filter(([k]) => k !== 'id')
      ),
    };

    const readSecurity = permToSecurity(entity.permissions.read);
    const writeSecurity = permToSecurity(entity.permissions.write);

    // Collection endpoints
    spec.paths[basePath] = {
      get: {
        tags: [tag],
        summary: `List all ${entity.name}s`,
        ...(readSecurity ? { security: readSecurity } : {}),
        parameters: entity.properties.map((p) => ({
          name: p.name,
          in: 'query',
          required: false,
          schema: { type: 'string' },
          description: `Filter by ${p.name}`,
        })),
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: { type: 'array', items: { $ref: `#/components/schemas/${entity.name}` } },
              },
            },
          },
        },
      },
      post: {
        tags: [tag],
        summary: `Create a ${entity.name}`,
        ...(writeSecurity ? { security: writeSecurity } : {}),
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: `#/components/schemas/${entity.name}Input` },
            },
          },
        },
        responses: {
          201: {
            description: 'Created',
            content: {
              'application/json': { schema: { $ref: `#/components/schemas/${entity.name}` } },
            },
          },
          400: { description: 'Bad Request' },
        },
      },
    };

    // Single item endpoints
    spec.paths[`${basePath}/{id}`] = {
      get: {
        tags: [tag],
        summary: `Get ${entity.name} by id`,
        ...(readSecurity ? { security: readSecurity } : {}),
        parameters: [idParam()],
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': { schema: { $ref: `#/components/schemas/${entity.name}` } },
            },
          },
          404: { description: 'Not Found' },
        },
      },
      patch: {
        tags: [tag],
        summary: `Update ${entity.name}`,
        ...(writeSecurity ? { security: writeSecurity } : {}),
        parameters: [idParam()],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: `#/components/schemas/${entity.name}Input` },
            },
          },
        },
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': { schema: { $ref: `#/components/schemas/${entity.name}` } },
            },
          },
          404: { description: 'Not Found' },
        },
      },
      delete: {
        tags: [tag],
        summary: `Delete ${entity.name}`,
        ...(writeSecurity ? { security: writeSecurity } : {}),
        parameters: [idParam()],
        responses: {
          200: { description: 'Deleted' },
          404: { description: 'Not Found' },
        },
      },
    };
  }

  // File storage endpoints
  for (const [bucketName] of Object.entries(core.files)) {
    const uploadPath = `/files/${bucketName}`;
    spec.paths[uploadPath] = {
      post: {
        tags: ['Files'],
        summary: `Upload file to ${bucketName}`,
        requestBody: {
          required: true,
          content: { 'multipart/form-data': { schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' } } } } },
        },
        responses: { 200: { description: 'Uploaded' } },
      },
    };
    spec.paths[`${uploadPath}/{file}`] = {
      get: {
        tags: ['Files'],
        summary: `Download file from ${bucketName}`,
        parameters: [{ name: 'file', in: 'path', required: true, schema: { type: 'string' } }],
        responses: { 200: { description: 'File content' }, 404: { description: 'Not Found' } },
      },
    };
  }

  return spec;
}

function buildEntitySchema(entity, allEntities) {
  const properties = { id: { type: 'integer', readOnly: true } };

  for (const prop of entity.properties) {
    properties[prop.name] = { type: openApiType(prop.type) };
  }

  for (const rel of entity.belongsTo) {
    const relName = typeof rel === 'string' ? rel : rel;
    const refEntity = allEntities[relName];
    if (refEntity) {
      properties[`${refEntity.tableName}_id`] = { type: 'integer' };
    }
  }

  return { type: 'object', properties };
}

function buildUserCollectionSchema(uc) {
  const properties = {
    id: { type: 'integer', readOnly: true },
    email: { type: 'string', format: 'email' },
  };
  for (const prop of uc.properties) {
    properties[prop.name] = { type: openApiType(prop.type) };
  }
  return { type: 'object', properties };
}

function buildUserCollectionInputSchema(uc) {
  const properties = {
    email: { type: 'string', format: 'email' },
    password: { type: 'string', format: 'password' },
  };
  for (const prop of uc.properties) {
    properties[prop.name] = { type: openApiType(prop.type) };
  }
  return {
    type: 'object',
    required: ['email', 'password'],
    properties,
  };
}

function permToSecurity(permission) {
  if (!permission || permission === 'public') return null;
  return [{ bearerAuth: [] }];
}

function openApiType(sqlType) {
  const map = {
    text: 'string',
    string: 'string',
    integer: 'integer',
    int: 'integer',
    number: 'number',
    float: 'number',
    real: 'number',
    boolean: 'boolean',
    bool: 'boolean',
    date: 'string',
    json: 'string',
  };
  return map[sqlType] || 'string';
}

function idParam() {
  return { name: 'id', in: 'path', required: true, schema: { type: 'integer' } };
}

function toSlug(name) {
  return name
    .replace(/([A-Z])/g, (m, p, offset) => (offset > 0 ? '-' : '') + p.toLowerCase())
    .replace(/^-/, '')
    .replace(/[^a-z0-9-]/g, '-');
}

module.exports = { generateOpenApiSpec };
